#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/fn"

tmp_branch=tmp-swap-before

if git show-ref --verify --quiet refs/heads/"$tmp_branch" ; then
  CMD git branch -D "$tmp_branch"
fi

CMD git branch "$tmp_branch"
CMD git reset head~2
CMD git add -A .
CMD git commit -C "$tmp_branch"
CMD git reset --hard "$tmp_branch"~
CMD git reset head@{1}
CMD git add -A .
CMD git commit -C "$tmp_branch"~
CMD git branch -D "$tmp_branch"
